// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBVdSTWDjsVFiDZ0IvgizXC-X8E97EgjQ',
    appId: '1:374832448445:web:54b6ff1df40f2d3ea1c8d4',
    messagingSenderId: '374832448445',
    projectId: 'chatapp-69260',
    authDomain: 'chatapp-69260.firebaseapp.com',
    storageBucket: 'chatapp-69260.appspot.com',
    measurementId: 'G-R591ZZTDYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdcceH0L99vk07YA1wd49EkFs-qLGQLCE',
    appId: '1:374832448445:android:f3910b9a5acc604ba1c8d4',
    messagingSenderId: '374832448445',
    projectId: 'chatapp-69260',
    storageBucket: 'chatapp-69260.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkR692tuXx7iR-NEbOwgaiUf1F6rdycnQ',
    appId: '1:374832448445:ios:c7059556e0363976a1c8d4',
    messagingSenderId: '374832448445',
    projectId: 'chatapp-69260',
    storageBucket: 'chatapp-69260.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkR692tuXx7iR-NEbOwgaiUf1F6rdycnQ',
    appId: '1:374832448445:ios:c7059556e0363976a1c8d4',
    messagingSenderId: '374832448445',
    projectId: 'chatapp-69260',
    storageBucket: 'chatapp-69260.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBVdSTWDjsVFiDZ0IvgizXC-X8E97EgjQ',
    appId: '1:374832448445:web:2c2e41ac48a67462a1c8d4',
    messagingSenderId: '374832448445',
    projectId: 'chatapp-69260',
    authDomain: 'chatapp-69260.firebaseapp.com',
    storageBucket: 'chatapp-69260.appspot.com',
    measurementId: 'G-49C8Y043FV',
  );
}
